Updated PDAR Aliases
vZMA/ZMA pull request #137
Opened 2021-04-09 22:27 UTC by migte

Placeholder - adding some stuff - WIP

Resolves #135

2021-04-20 01:18 UTC, erikquinn requested changes

2021-04-20 01:18 UTC, erikquinn commented on docs/alias/Alias.txt
> +.MY280 .MSG ZMA_INFO WINCO CHRRI DOLIE Y280
Please add support for the more verbose MIA:
`.MY280` / `.MIAY280` / `.FLLY280` / `.FY280`

2021-04-20 01:18 UTC, erikquinn commented on docs/alias/Alias.txt
> +.ROUTER .openurl https://flightaware.com/analysis/route.rvt?origin=KRSW&destination=$uc($1)
After the below change, why not just remove these as they have no benefit over `.route`?

2021-04-20 01:18 UTC, erikquinn commented on docs/alias/Alias.txt
> +.ROUTE .openurl https://flightaware.com/analysis/route.rvt?origin=$uc($1)&destination=$uc($2)
Why not simply pull the FP data? eg:
`.ROUTE .openurl https://flightaware.com/analysis/route.rvt?origin=$dep&destination=$arr`

2021-04-20 01:18 UTC, erikquinn commented on docs/alias/Alias.txt
> +.HIEA $radioname(), expect $uc($1) Runway $uc($2) approach.
🎉

2021-04-20 01:21 UTC, migte commented on docs/alias/Alias.txt
> +.ROUTER .openurl https://flightaware.com/analysis/route.rvt?origin=KRSW&destination=$uc($1)
even more good idea

2021-04-20 01:21 UTC, migte commented on docs/alias/Alias.txt
> +.MY280 .MSG ZMA_INFO WINCO CHRRI DOLIE Y280
Rgr

2022-06-17 13:24 UTC, migte commented
@erikquinn Since metroplex and all the changes that have happened, I can finish up this branch/PR to include the .route commands but I should leave out, if not clean out, all the hedly arkes etc stuff, right?

2022-06-19 19:49 UTC, erikquinn commented
@migte Yeah, I guess update what you can, and what you can't, _comment it out_. Leaving it still present and commented out will make it easier in the future when we come back to update and reimplement the same concept with the newer routes and such.

2022-10-25 16:29 UTC, erikquinn commented
@migte bump?

2022-10-25 16:31 UTC, erikquinn commented
or @ksnifte, maybe you could clean this one up? Want to get it done before #173.

2022-10-25 20:54 UTC, ksnifte commented
Is the only thing left to do just clean out the pre-Metroplex DPs?

2022-10-27 04:46 UTC, erikquinn commented
yep, to remove any changes made irrelevent by metroplex, and address any outstanding comments. Then request a review from me again. Planning to merge this one first.

2023-06-19 04:18 UTC, erikquinn commented on docs/alias/Alias.txt
> +.MY280 .MSG ZMA_INFO WINCO CHRRI DOLIE Y280
no longer relevant, have been removed.

2023-06-19 04:18 UTC, erikquinn commented on docs/alias/Alias.txt
> +.ROUTER .openurl https://flightaware.com/analysis/route.rvt?origin=KRSW&destination=$uc($1)
reduced to one

2023-06-19 04:34 UTC, merged