93 Adding new JAX center frequencies to vERAM, vSTARS and VRC POF
vZMA/ZMA pull request #95
Opened 2020-09-06 23:20 UTC by patrgl

Added the positions for the POF, vERAM, vSTARs (PBI, TPA) files

2020-09-08 16:04 UTC, erikquinn requested changes
Also looks like the vERAM/vSTARS files don't match what's in the POF currently (I see two entries for J30, for example).

2020-09-08 16:04 UTC, erikquinn commented on docs/pof/ZMA.pof
> +JAX_16_CTR:Jacksonville Center:125.175:J16:J:JAX:CTR:JAX:CTR:1001:1047
Compared to the above, can you add secondary entries for any position whose frequency ends in a .x2 or .x7 to include both the .x20 and .x25 (etc) variations?

Really, people should know to use .175, but it doesn't always happen. And if it's defined in the POF as .175 and they prim on .170, the client doesn't think it is this sector anymore. By including the same line twice, once with .175 and once with .170, the handoff code for J16 will always be `J16`, regardless of whether their controller prims on .170 or .175.

2020-09-08 16:20 UTC, patrgl commented on docs/pof/ZMA.pof
> +JAX_16_CTR:Jacksonville Center:125.175:J16:J:JAX:CTR:JAX:CTR:1001:1047
Ahh completely glossed over that! I'll put that in later tonight :)

2020-09-13 16:07 UTC, erikquinn requested changes
Missed a spot! Otherwise looks good to me

2020-09-13 16:07 UTC, erikquinn commented on docs/pof/ZMA.pof
> +JAX_50_CTR:Jacksonville Center:135.970:J50:J:JAX:CTR:JAX:CTR:1001:1047
135.975 / 135.970

2020-09-13 23:37 UTC, erikquinn commented on docs/pof/ZMA.pof
> +JAX_50_CTR:Jacksonville Center:135.970:J50:J:JAX:CTR:JAX:CTR:1001:1047
done

2020-09-13 23:57 UTC, erikquinn approved these changes
Looks good to me now.

@patrgl Just an FYI, be very careful editing the vSTARs/vERAM files by hand. It's easy enough to do, but leads to the possibility of breaking. Where you had `adjacent` instead of `Adjacent`, it broke the file and vSTARS couldn't load it because it was corrupt. So I'd recommend the (more tedious, but more reliable) approach of 7zip to *.gz, import, edit in the menus, export, 7zip to "extract here".

2020-09-14 00:01 UTC, merged